/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v0/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List agents
         * @description List all cloud agents for the authenticated user
         */
        get: operations["listAgents"];
        put?: never;
        /**
         * Launch an agent
         * @description Start a new cloud agent to work on your repository
         */
        post: operations["createAgent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v0/agents/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Agent status
         * @description Retrieve the current status and results of a cloud agent
         */
        get: operations["getAgent"];
        put?: never;
        post?: never;
        /**
         * Delete an agent
         * @description Delete a cloud agent. This action is permanent and cannot be undone.
         */
        delete: operations["deleteAgent"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v0/agents/{id}/followup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add followup
         * @description Add a followup instruction to an existing cloud agent
         */
        post: operations["addFollowup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v0/agents/{id}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stop an agent
         * @description Stop a running cloud agent. This pauses the agent's execution without deleting it. Stopped agents cannot be resumed.
         */
        post: operations["stopAgent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v0/agents/{id}/conversation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get agent conversation
         * @description Retrieve the conversation history of a cloud agent, including all user prompts and assistant responses
         */
        get: operations["getAgentConversation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v0/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * API key info
         * @description Retrieve information about the API key being used for authentication
         */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v0/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List available models
         * @description Retrieve a list of recommended models for cloud agents
         */
        get: operations["listModels"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v0/repositories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List GitHub repositories
         * @description Retrieve a list of GitHub repositories accessible to the authenticated user
         */
        get: operations["listRepositories"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ImageDimension: {
            /** @description Width must be a positive integer */
            width: number;
            /** @description Height must be a positive integer */
            height: number;
        };
        Image: {
            /**
             * @description Base64 encoded image data
             * @example iVBORw0KGgoAAAANSUhEUgAA...
             */
            data: string;
            dimension?: components["schemas"]["ImageDimension"];
        };
        CreateAgentRequest: {
            prompt: {
                /**
                 * @description The task or instructions for the agent to execute
                 * @example Add a README.md file with installation instructions
                 */
                text: string;
                /**
                 * @description Optional array of base64 encoded images (max 5)
                 * @example [
                 *       {
                 *         "data": "iVBORw0KGgoAAAANSUhEUgAA...",
                 *         "dimension": {
                 *           "width": 1024,
                 *           "height": 768
                 *         }
                 *       }
                 *     ]
                 */
                images?: components["schemas"]["Image"][];
            };
            /**
             * @description The LLM to use
             * @example claude-4-sonnet
             */
            model?: string;
            source: {
                /**
                 * @description The GitHub repository URL. Required unless prUrl is provided.
                 * @example https://github.com/your-org/your-repo
                 */
                repository?: string;
                /**
                 * @description Git ref (branch/tag) to use as the base branch
                 * @example main
                 */
                ref?: string;
                /**
                 * Format: uri
                 * @description GitHub pull request URL. When provided, the agent works on this PR's repository and branches. Mutually exclusive with repository/ref.
                 * @example https://github.com/your-org/your-repo/pull/123
                 */
                prUrl?: string;
            };
            target?: {
                /**
                 * @description Whether to automatically create a pull request when the agent completes
                 * @default false
                 */
                autoCreatePr: boolean;
                /**
                 * @description Whether to open the pull request as the Cursor GitHub App instead of as the user. Only applies if autoCreatePr is true.
                 * @default false
                 */
                openAsCursorGithubApp: boolean;
                /**
                 * @description Whether to skip adding the user as a reviewer to the pull request. Only applies if autoCreatePr is true and the PR is opened as the Cursor GitHub App.
                 * @default false
                 */
                skipReviewerRequest: boolean;
                /**
                 * @description Custom branch name for the agent to create
                 * @example feature/add-readme
                 */
                branchName?: string;
                /**
                 * @description Whether to create a new branch (true) or use the PR's existing head branch (false). Only applies when source.prUrl is provided.
                 * @default true
                 */
                autoBranch: boolean;
            };
            webhook?: {
                /**
                 * Format: uri
                 * @description URL to receive webhook notifications about agent status changes
                 * @example https://example.com/webhooks/cursor-agent
                 */
                url: string;
                /**
                 * @description Secret key for webhook payload verification
                 * @example your-webhook-secret-key-minimum-32-characters
                 */
                secret?: string;
            };
        };
        Error: {
            error?: {
                /** @description Human-readable error message */
                message?: string;
                /** @description Machine-readable error code */
                code?: string;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listAgents: {
        parameters: {
            query?: {
                /** @description Number of cloud agents to return */
                limit?: number;
                /** @description Pagination cursor from the previous response */
                cursor?: string;
                /** @description Filter agents by pull request URL */
                prUrl?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Agents retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description List of agents */
                        agents: {
                            /**
                             * @description Unique identifier for the cloud agent
                             * @example bc_abc123
                             */
                            id: string;
                            /**
                             * @description Name for the agent
                             * @example Add README Documentation
                             */
                            name: string;
                            /**
                             * @description Current status of the cloud agent
                             * @example RUNNING
                             * @enum {string}
                             */
                            status: "RUNNING" | "FINISHED" | "ERROR" | "CREATING" | "EXPIRED";
                            source: {
                                /**
                                 * @description The GitHub repository URL
                                 * @example https://github.com/your-org/your-repo
                                 */
                                repository?: string;
                                /**
                                 * @description Git ref (branch/tag) used as the base branch
                                 * @example main
                                 */
                                ref?: string;
                            };
                            target: {
                                /**
                                 * @description The Git branch name where the agent is working
                                 * @example cursor/add-readme-1234
                                 */
                                branchName?: string;
                                /**
                                 * @description URL to view the agent in Cursor Web
                                 * @example https://cursor.com/agents?id=bc_abc123
                                 */
                                url: string;
                                /**
                                 * @description URL to view the pull request in GitHub, if any
                                 * @example https://github.com/your-org/your-repo/pull/1234
                                 */
                                prUrl?: string;
                                /**
                                 * @description Whether a pull request will be automatically created
                                 * @example false
                                 */
                                autoCreatePr?: boolean;
                                /**
                                 * @description Whether the pull request will be opened as the Cursor GitHub App
                                 * @example false
                                 */
                                openAsCursorGithubApp?: boolean;
                                /**
                                 * @description Whether to skip adding the user as a reviewer to the pull request
                                 * @example false
                                 */
                                skipReviewerRequest?: boolean;
                            };
                            /**
                             * @description Summary of the agent's work
                             * @example Added README.md with installation instructions and usage examples
                             */
                            summary?: string;
                            /**
                             * Format: date-time
                             * @description When the agent was created
                             * @example 2024-01-15T10:30:00Z
                             */
                            createdAt: string;
                        }[];
                        /**
                         * @description Cursor for fetching the next page of results
                         * @example bc_def456
                         */
                        nextCursor?: string;
                    };
                };
            };
            /** @description Invalid request - bad query parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unauthorized - invalid or missing API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Forbidden - insufficient permissions */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    createAgent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAgentRequest"];
            };
        };
        responses: {
            /** @description Agent created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @description Unique identifier for the cloud agent
                         * @example bc_abc123
                         */
                        id: string;
                        /**
                         * @description Name for the agent
                         * @example Add README Documentation
                         */
                        name: string;
                        /**
                         * @description Initial status of the newly created agent
                         * @example CREATING
                         * @enum {string}
                         */
                        status: "CREATING";
                        source: {
                            /**
                             * @description The GitHub repository URL
                             * @example https://github.com/your-org/your-repo
                             */
                            repository: string;
                            /**
                             * @description Git ref (branch/tag) used as the base branch
                             * @example main
                             */
                            ref?: string;
                        };
                        target: {
                            /**
                             * @description The Git branch name where the agent is working
                             * @example cursor/add-readme-1234
                             */
                            branchName?: string;
                            /**
                             * @description URL to view the agent in Cursor Web
                             * @example https://cursor.com/agents?id=bc_abc123
                             */
                            url: string;
                            /**
                             * @description URL of the pull request, if agent was created from a PR
                             * @example https://github.com/your-org/your-repo/pull/123
                             */
                            prUrl?: string;
                            /**
                             * @description Whether a pull request will be automatically created
                             * @example false
                             */
                            autoCreatePr?: boolean;
                            /**
                             * @description Whether the pull request will be opened as the Cursor GitHub App
                             * @example false
                             */
                            openAsCursorGithubApp?: boolean;
                            /**
                             * @description Whether to skip adding the user as a reviewer to the pull request
                             * @example false
                             */
                            skipReviewerRequest?: boolean;
                        };
                        /**
                         * Format: date-time
                         * @description When the agent was created
                         * @example 2024-01-15T10:30:00Z
                         */
                        createdAt: string;
                    };
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unauthorized - invalid or missing API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Forbidden - insufficient permissions, plan limits exceeded, or storage full */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getAgent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier for the cloud agent */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Agent details retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @description Unique identifier for the cloud agent
                         * @example bc_abc123
                         */
                        id: string;
                        /**
                         * @description Name for the agent
                         * @example Add README Documentation
                         */
                        name: string;
                        /**
                         * @description Current status of the cloud agent
                         * @example RUNNING
                         * @enum {string}
                         */
                        status: "RUNNING" | "FINISHED" | "ERROR" | "CREATING" | "EXPIRED";
                        source: {
                            /**
                             * @description The GitHub repository URL
                             * @example https://github.com/your-org/your-repo
                             */
                            repository?: string;
                            /**
                             * @description Git ref (branch/tag) used as the base branch
                             * @example main
                             */
                            ref?: string;
                        };
                        target: {
                            /**
                             * @description The Git branch name where the agent is working
                             * @example cursor/add-readme-1234
                             */
                            branchName?: string;
                            /**
                             * @description URL to view the agent in Cursor Web
                             * @example https://cursor.com/agents?id=bc_abc123
                             */
                            url: string;
                            /**
                             * @description URL to view the pull request in GitHub, if any
                             * @example https://github.com/your-org/your-repo/pull/1234
                             */
                            prUrl?: string;
                            /**
                             * @description Whether a pull request will be automatically created
                             * @example false
                             */
                            autoCreatePr?: boolean;
                            /**
                             * @description Whether the pull request will be opened as the Cursor GitHub App
                             * @example false
                             */
                            openAsCursorGithubApp?: boolean;
                            /**
                             * @description Whether to skip adding the user as a reviewer to the pull request
                             * @example false
                             */
                            skipReviewerRequest?: boolean;
                        };
                        /**
                         * @description Summary of the agent's work
                         * @example Added README.md with installation instructions and usage examples
                         */
                        summary?: string;
                        /**
                         * Format: date-time
                         * @description When the agent was created
                         * @example 2024-01-15T10:30:00Z
                         */
                        createdAt: string;
                    };
                };
            };
            /** @description Invalid request - bad agent ID format */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unauthorized - invalid or missing API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Forbidden - insufficient permissions */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Agent not found or access denied */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    deleteAgent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier for the cloud agent */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Agent deleted successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @description Unique identifier for the cloud agent
                         * @example bc_abc123
                         */
                        id: string;
                    };
                };
            };
            /** @description Invalid request - bad agent ID format */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unauthorized - invalid or missing API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Forbidden - insufficient permissions */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Agent not found or access denied */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Conflict - agent is deleted or archived */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    addFollowup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier for the cloud agent */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    prompt: {
                        /**
                         * @description The followup instruction for the agent
                         * @example Also add a section about troubleshooting
                         */
                        text: string;
                        /**
                         * @description Optional array of base64 encoded images (max 5)
                         * @example [
                         *       {
                         *         "data": "iVBORw0KGgoAAAANSUhEUgAA...",
                         *         "dimension": {
                         *           "width": 1024,
                         *           "height": 768
                         *         }
                         *       }
                         *     ]
                         */
                        images?: components["schemas"]["Image"][];
                    };
                };
            };
        };
        responses: {
            /** @description Followup added successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @description Unique identifier for the cloud agent
                         * @example bc_abc123
                         */
                        id: string;
                    };
                };
            };
            /** @description Invalid request - bad agent ID format or invalid request body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unauthorized - invalid or missing API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Forbidden - insufficient permissions */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Agent not found or access denied */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Conflict - agent is deleted or archived */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    stopAgent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier for the cloud agent */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Agent stopped successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @description Unique identifier for the cloud agent
                         * @example bc_abc123
                         */
                        id: string;
                    };
                };
            };
            /** @description Invalid request - bad agent ID format */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unauthorized - invalid or missing API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Forbidden - insufficient permissions */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Agent not found or access denied */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Conflict - agent is deleted or archived */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getAgentConversation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier for the cloud agent */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Conversation retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @description Unique identifier for the cloud agent
                         * @example bc_abc123
                         */
                        id: string;
                        /** @description Array of conversation messages ordered chronologically */
                        messages: {
                            /**
                             * @description Unique identifier for the message
                             * @example msg_123
                             */
                            id: string;
                            /**
                             * @description Type of message - either from the user or the model
                             * @example user_message
                             * @enum {string}
                             */
                            type: "user_message" | "assistant_message";
                            /**
                             * @description The content of the message
                             * @example Add a README.md file with installation instructions
                             */
                            text: string;
                        }[];
                    };
                };
            };
            /** @description Invalid request - bad agent ID format */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unauthorized - invalid or missing API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Forbidden - insufficient permissions */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Agent not found or access denied */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Conflict - agent is deleted or archived */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description API key information retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @description The name of the API key
                         * @example Production API Key
                         */
                        apiKeyName: string;
                        /**
                         * Format: date-time
                         * @description When the API key was created
                         * @example 2024-01-15T10:30:00Z
                         */
                        createdAt: string;
                        /**
                         * Format: email
                         * @description Email address of the user who owns the API key (if available)
                         * @example developer@example.com
                         */
                        userEmail?: string;
                    };
                };
            };
            /** @description Unauthorized - invalid or missing API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description API key not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listModels: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Models retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @description Array of available model names
                         * @example [
                         *       "claude-4-sonnet-thinking",
                         *       "gpt-5.2",
                         *       "claude-4.5-sonnet-thinking"
                         *     ]
                         */
                        models: string[];
                    };
                };
            };
            /** @description Unauthorized - invalid or missing API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listRepositories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Repositories retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Array of GitHub repositories the user has access to */
                        repositories: {
                            /**
                             * @description The owner of the repository (user or organization)
                             * @example your-org
                             */
                            owner: string;
                            /**
                             * @description The name of the repository
                             * @example your-repo
                             */
                            name: string;
                            /**
                             * Format: uri
                             * @description The full URL to the GitHub repository
                             * @example https://github.com/your-org/your-repo
                             */
                            repository: string;
                        }[];
                    };
                };
            };
            /** @description Unauthorized - invalid or missing API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
